python eval.py --config configs/turkishmscoco/turkishmscoco_exp3_base16_electra.yaml --weights experiments/turkishmscoco_experiments/turkishmscoco_exp3_base16_electra/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/turkishmscoco/turkishmscoco_exp3_base16_electra.yaml --weights experiments/turkishmscoco_experiments/turkishmscoco_exp3_base16_electra/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/turkishmscoco/turkishmscoco_exp3_base16_electra.yaml --weights experiments/turkishmscoco_experiments/turkishmscoco_exp3_base16_electra/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/turkishmscoco/turkishmscoco_exp3_base16_electra.yaml --weights experiments/turkishmscoco_experiments/turkishmscoco_exp3_base16_electra/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/turkishmscoco/turkishmscoco_exp1_base16_electra_dino2.yaml --weights experiments/turkishmscoco_experiments/turkishmscoco_exp1_base16_electra_dino2/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/turkishmscoco/turkishmscoco_exp1_base16_electra_dino2.yaml --weights experiments/turkishmscoco_experiments/turkishmscoco_exp1_base16_electra_dino2/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/turkishmscoco/turkishmscoco_exp1_base16_electra_dino2.yaml --weights experiments/turkishmscoco_experiments/turkishmscoco_exp1_base16_electra_dino2/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/turkishmscoco/turkishmscoco_exp1_base16_electra_dino2.yaml --weights experiments/turkishmscoco_experiments/turkishmscoco_exp1_base16_electra_dino2/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/turkishmscoco/turkishmscoco_exp2_base16_electra_dino2.yaml --weights experiments/turkishmscoco_experiments/turkishmscoco_exp2_base16_electra_dino2/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/turkishmscoco/turkishmscoco_exp2_base16_electra_dino2.yaml --weights experiments/turkishmscoco_experiments/turkishmscoco_exp2_base16_electra_dino2/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/turkishmscoco/turkishmscoco_exp2_base16_electra_dino2.yaml --weights experiments/turkishmscoco_experiments/turkishmscoco_exp2_base16_electra_dino2/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/turkishmscoco/turkishmscoco_exp2_base16_electra_dino2.yaml --weights experiments/turkishmscoco_experiments/turkishmscoco_exp2_base16_electra_dino2/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/coco/coco_exp1_base16_electra.yaml --weights experiments/coco_experiments/coco_exp1_base16_electra/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/coco/coco_exp1_base16_electra.yaml --weights experiments/coco_experiments/coco_exp1_base16_electra/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/coco/coco_exp1_base16_electra.yaml --weights experiments/coco_experiments/coco_exp1_base16_electra/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/coco/coco_exp1_base16_electra.yaml --weights experiments/coco_experiments/coco_exp1_base16_electra/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/coco/coco_exp1_base16_electra_dino2.yaml --weights experiments/coco_experiments/coco_exp1_base16_electra_dino2/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/coco/coco_exp1_base16_electra_dino2.yaml --weights experiments/coco_experiments/coco_exp1_base16_electra_dino2/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/coco/coco_exp1_base16_electra_dino2.yaml --weights experiments/coco_experiments/coco_exp1_base16_electra_dino2/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/coco/coco_exp1_base16_electra_dino2.yaml --weights experiments/coco_experiments/coco_exp1_base16_electra_dino2/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/coco/coco_exp2_base16_electra_dino2.yaml --weights experiments/coco_experiments/coco_exp2_base16_electra_dino2/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/coco/coco_exp2_base16_electra_dino2.yaml --weights experiments/coco_experiments/coco_exp2_base16_electra_dino2/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/coco/coco_exp2_base16_electra_dino2.yaml --weights experiments/coco_experiments/coco_exp2_base16_electra_dino2/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/coco/coco_exp2_base16_electra_dino2.yaml --weights experiments/coco_experiments/coco_exp2_base16_electra_dino2/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/flickr30k/flickr30k_exp1_base16_electra.yaml --weights experiments/flickr30k_experiments/flickr30k_exp1_base16_electra/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/flickr30k/flickr30k_exp1_base16_electra.yaml --weights experiments/flickr30k_experiments/flickr30k_exp1_base16_electra/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/flickr30k/flickr30k_exp1_base16_electra.yaml --weights experiments/flickr30k_experiments/flickr30k_exp1_base16_electra/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/flickr30k/flickr30k_exp1_base16_electra.yaml --weights experiments/flickr30k_experiments/flickr30k_exp1_base16_electra/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/flickr30k/flickr30k_exp1_base16_electra_dino2.yaml --weights experiments/flickr30k_experiments/flickr30k_exp1_base16_electra_dino2/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/flickr30k/flickr30k_exp1_base16_electra_dino2.yaml --weights experiments/flickr30k_experiments/flickr30k_exp1_base16_electra_dino2/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/flickr30k/flickr30k_exp1_base16_electra_dino2.yaml --weights experiments/flickr30k_experiments/flickr30k_exp1_base16_electra_dino2/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/flickr30k/flickr30k_exp1_base16_electra_dino2.yaml --weights experiments/flickr30k_experiments/flickr30k_exp1_base16_electra_dino2/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/flickr30k/flickr30k_exp2_base16_electra_dino2.yaml --weights experiments/flickr30k_experiments/flickr30k_exp2_base16_electra_dino2/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/flickr30k/flickr30k_exp2_base16_electra_dino2.yaml --weights experiments/flickr30k_experiments/flickr30k_exp2_base16_electra_dino2/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/flickr30k/flickr30k_exp2_base16_electra_dino2.yaml --weights experiments/flickr30k_experiments/flickr30k_exp2_base16_electra_dino2/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/flickr30k/flickr30k_exp2_base16_electra_dino2.yaml --weights experiments/flickr30k_experiments/flickr30k_exp2_base16_electra_dino2/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/tasviret/tasviret_exp1_base16_electra.yaml --weights experiments/tasviret_experiments/tasviret_exp1_base16_electra/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/tasviret/tasviret_exp1_base16_electra.yaml --weights experiments/tasviret_experiments/tasviret_exp1_base16_electra/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/tasviret/tasviret_exp1_base16_electra.yaml --weights experiments/tasviret_experiments/tasviret_exp1_base16_electra/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/tasviret/tasviret_exp1_base16_electra.yaml --weights experiments/tasviret_experiments/tasviret_exp1_base16_electra/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/tasviret/tasviret_exp1_base16_electra_dino2.yaml --weights experiments/tasviret_experiments/tasviret_exp1_base16_electra_dino2/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/tasviret/tasviret_exp1_base16_electra_dino2.yaml --weights experiments/tasviret_experiments/tasviret_exp1_base16_electra_dino2/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/tasviret/tasviret_exp1_base16_electra_dino2.yaml --weights experiments/tasviret_experiments/tasviret_exp1_base16_electra_dino2/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/tasviret/tasviret_exp1_base16_electra_dino2.yaml --weights experiments/tasviret_experiments/tasviret_exp1_base16_electra_dino2/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/tasviret/tasviret_exp2_base16_electra_dino2.yaml --weights experiments/tasviret_experiments/tasviret_exp2_base16_electra_dino2/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/tasviret/tasviret_exp2_base16_electra_dino2.yaml --weights experiments/tasviret_experiments/tasviret_exp2_base16_electra_dino2/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/tasviret/tasviret_exp2_base16_electra_dino2.yaml --weights experiments/tasviret_experiments/tasviret_exp2_base16_electra_dino2/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/tasviret/tasviret_exp2_base16_electra_dino2.yaml --weights experiments/tasviret_experiments/tasviret_exp2_base16_electra_dino2/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/turkcap8m/turkcap8m_exp1_base16_berturk.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp1_base16_berturk/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/turkcap8m/turkcap8m_exp1_base16_berturk.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp1_base16_berturk/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/turkcap8m/turkcap8m_exp1_base16_berturk.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp1_base16_berturk/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/turkcap8m/turkcap8m_exp1_base16_berturk.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp1_base16_berturk/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/turkcap8m/turkcap8m_exp1_base16_electra.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp1_base16_electra/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/turkcap8m/turkcap8m_exp1_base16_electra.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp1_base16_electra/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/turkcap8m/turkcap8m_exp1_base16_electra.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp1_base16_electra/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/turkcap8m/turkcap8m_exp1_base16_electra.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp1_base16_electra/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/turkcap8m/turkcap8m_exp1_base16_electra_dino2.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp1_base16_electra_dino2/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/turkcap8m/turkcap8m_exp1_base16_electra_dino2.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp1_base16_electra_dino2/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/turkcap8m/turkcap8m_exp1_base16_electra_dino2.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp1_base16_electra_dino2/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/turkcap8m/turkcap8m_exp1_base16_electra_dino2.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp1_base16_electra_dino2/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco

python eval.py --config configs/turkcap8m/turkcap8m_exp2_base16_electra_dino2.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp2_base16_electra_dino2/model_last.pth --dataset coco --test-json data/coco/annotations/coco_karpathy_test_gt_tr.json --test-data data/coco
python eval.py --config configs/turkcap8m/turkcap8m_exp2_base16_electra_dino2.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp2_base16_electra_dino2/model_last.pth --dataset flickr --test-json data/flickr/flickr30k_test_trV2.json --test-data data/flickr
python eval.py --config configs/turkcap8m/turkcap8m_exp2_base16_electra_dino2.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp2_base16_electra_dino2/model_last.pth --dataset tasviret --test-json data/tasvir-et/tasvir_test.json --test-data data/flickr/flickr30k-images
python eval.py --config configs/turkcap8m/turkcap8m_exp2_base16_electra_dino2.yaml --weights experiments/turkcap8m_experiments/turkcap8m_exp2_base16_electra_dino2/model_last.pth --dataset TurkishMSCOCO --test-json data/TurkishMSCOCO/TurkishMSCOCO_test_gt_tr.json --test-data data/coco


