
seed: 42
gpu: 0
save_dir: experiments/turkcap8m_experiments
save_name: turkcap8m_exp2_base16_electra_dino2
overwrite: ~

# modelş
model:
  dino2: dinov2_vitl14
  bert: dbmdz/electra-base-turkish-mc4-cased-discriminator
  max_length: 35
  proj: True
  proj_num_head: 16

# optimizer
lr: 5e-5
lr_proj: 5e-4
betas: [0.9, 0.99]
weight_decay: 0.0
num_workers: 8

batch_size: 64
grad_acc: 4
max_iter: 500000
warm_up_iter: 10000
num_eval_iter: 10000
target_metric: 'Bleu_4' # Bleu_1 Bleu_2 Bleu_3 Bleu_4 METEOR ROUGE_L CIDEr SPICE

# dataset
train_dataset_name: turkcap8m
train_dataset_root: "/media/serdar/Works2T/Datasets/Captioning/TurkCap8M"
train_json_path: "/media/serdar/Works2T/Datasets/Captioning/TurkCap8M/info_ofa_blip_fusecap_blip2_translated.json"


test_dataset_name: coco-karphaty
test_dataset_root: "/media/serdar/BackUp/PycharmProjects/TR-CLIP-Captioning/Data/coco/"
val_json_path: "/media/serdar/BackUp/PycharmProjects/TR-CLIP-Captioning/Data/coco/annotations/coco_karpathy_val_gt_tr.json"

