
seed: 42
gpu: 0
save_dir: experiments/turkishmscoco_experiments
save_name: turkishmscoco_exp2_base16_electra_dino2
overwrite: ~
pretrain: experiments/turkcap8m_experiments/turkcap8m_exp2_base16_electra_dino2/model_last.pth

# model
model:
  dino2: dinov2_vitl14
  bert: dbmdz/electra-base-turkish-mc4-cased-discriminator
  max_length: 35
  proj: True
  proj_num_head: 16

# optimizer
lr: 5e-6
lr_proj: 5e-5
betas: [0.9, 0.99]
weight_decay: 0.0
num_workers: 8

batch_size: 64
grad_acc: 4
max_iter: 50000
warm_up_iter: 1000
num_eval_iter: 5000
target_metric: 'Bleu_4' # Bleu_1 Bleu_2 Bleu_3 Bleu_4 METEOR ROUGE_L CIDEr SPICE

# dataset
train_dataset_name: coco-karphaty
train_dataset_root: "/media/serdar/Works2T/Datasets/Captioning/coco"
train_json_path: "/media/serdar/Works2T/Datasets/Captioning/TurkishMSCOCO/TurkishMSCOCO_train_tr.json"


test_dataset_name: coco-karphaty
test_dataset_root: "/media/serdar/Works2T/Datasets/Captioning/coco"
val_json_path: "/media/serdar/Works2T/Datasets/Captioning/TurkishMSCOCO/TurkishMSCOCO_val_gt_tr.json"

